#!/usr/bin/python3

import os
from PIL import Image
from pymediainfo import MediaInfo

print("[#] => Attempting to index media files...")

html_path = "index.html"

directory = os.listdir(".")

columns = 5

def html_write(content):
    with open(html_path, "w") as writefile:
        writefile.write(content)
        writefile.close()

def html_append(content):
    with open(html_path, "a") as file:
        file.write(content)
        file.close()

def html_prepend(content):
    with open(html_path, 'r+') as f:
        f.seek(0, 0)
        f.write(content.rstrip('\r\n') + '\n' + content)

def is_image(path):
    try:
        im = Image.open(path)
        im.close()
        return True
    except IOError:
        return False

def get_type(path):
    fileInfo = MediaInfo.parse(path)
    for track in fileInfo.tracks:
        if track.track_type == "Image":
            return 1
        elif track.track_type == "Video":
            return 2
        elif track.track_type == "Audio":
            return 3
    return 4


# MAIN

html_write("""


<!DOCTYPE html>

<!-- autogenerated index.html -->

<html>
<head>
    <link rel="stylesheet" href="styles.css">
</head>
<body>

<h1 style='text-align: center;'>~ Captured Server Contents ~</h1> 

<div>
""")

counter = 0

image_counter = 0
video_counter = 0
audio_counter = 0
undefined_counter = 0

for file in directory:
    counter += 1

    image = is_image(file)

    if image:
        html_append(f"<img src='{file}'>\n")
        image_counter += 1
    else:
        media_type = get_type(file) 
        if media_type == 1:    
            html_append(f"<img src='{file}'>\n")
            image_counter += 1
        elif media_type == 2:
            html_append(f" <video controls>\n<source src={file} type='video/mp4'>\nYour browser does not support the video tag.\n</video>")
            video_counter += 1
        elif media_type == 3:
            html_append(f"<audio src='{file}' controls>\nYour browser does not support the <code>audio</code> element\n</audio>")
            audio_counter += 1
        else:
            if file not in ["serve.py", "index.html", "styles.css", "clean_videos.py"]:
                html_append(f"<a href='{file}'>{file}</a>")
                undefined_counter += 1

    if counter == columns:
        html_append("</div>\n\n<div>\n")
        counter = 0

html_append("\n</body> \n</html>")

print(f"================\nImages    : {image_counter}\nVideos    : {video_counter}\nAudios    : {audio_counter}\nUndefined : {undefined_counter}\n\033[14;1;14mTOTAL\033[0m     : {image_counter + video_counter + audio_counter + undefined_counter}\n================")
print("[+] => Indexed HTML at index.html")
print("[+] => Serving contents at port 8000 ...")

os.system("python -m http.server")
